
version: '3.8'

services:
  indijobs-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - "8085:8085"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8085/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.indijobs.rule=Host(`localhost`)"
      - "traefik.http.services.indijobs.loadbalancer.server.port=8085"

  # Optional: Add a reverse proxy
  nginx-proxy:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./proxy.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - indijobs-app
    restart: unless-stopped
